#SnakeMake yaml configuration file
#This file only sets the master configuration, and some parameters of the
#build, to be used to by Snakemake. The more detailed configuration
#settings are fixed in the respective configuration directories

#Valid options: Ghana 
#SnakeMake yaml configuration file

dirs:
    input: '/dmidata/projects/klimaatlas/pipeline/data/DAY_EUR11_DENMARK/'
    output: 'outputs/'
    logs: 'logs'
    scratchDir: './scratch/'
    indicators: 'indicators'
domain:
    xmin: -4
    xmax: 2
    dx: 0.1
    ymin: 4
    ymax: 12
    dy: 0.1
    method: 'bilinear'  #Regridding method used by xesmf.Regridder()
percentiles: [10,50,90]
periods:
    period1:
        id: 1
        name: 'Historical (1981-2005)'
        start: 1981
        end: 2005
    period2:
        id: 2
        name: 'Start of century (2011-2040)'
        start: 2011
        end: 2040
    period3:
        id: 3
        name: 'Mid-century (2041-2070)'
        start: 2041
        end: 2070
    period4:
        id: 4
        name: 'End-of-century (2071-2100)'
        start: 2071
        end: 2100
    
