# Basic configuration file
#---------------------------
# This configuration file is intended to be used as a basic example and test
# dataset for the KAPy suite. It is loosely based on the configuration used in the
# Ghana Climate Atlas, but with simplifications to make it run faster. Sample datasets
# can be downloaded from https://download.dmi.dk/Research_Projects/KAPy/

configurationTables:
    inputs:     '../config/testcase_3/inputs.tsv'
    indicators: '../config/testcase_3/indicators.tsv'
    scenarios:  '../config/testcase_3/scenarios.tsv'
    periods:    '../config/testcase_3/periods.tsv'
    seasons:    '../config/testcase_3/seasons.tsv'
dirs:
    variables:  '../results/1.variables'
    indicators: '../results/2.indicators'
    regridded:  '../results/3.commmon_grid'
    ensstats:   '../results/4.ensstats'
    arealstats: '../results/5.areal_statistics'
    plots:      '../results/6.plots'
    netcdf:     '../results/7.netcdf'

# Configuration options------------------------------------
arealstats:
    calcForMembers: False
ensembles:
    upperPercentile: 99
    centralPercentile: 95
    lowerPercentile: 1
cutouts:
    method: None
outputGrid:
    regriddingEngine: None
