#Ghana configuration file

domain:
    xmin: -4
    xmax: 2
    dx: 0.1
    ymin: 4
    ymax: 12
    dy: 0.1
download:
    ESGF: './configs/Ghana/ESGF.yaml'
indicators:
    101:
        id: 101
        name: 'Annual mean temperature (C)'
        variables: 'tas'
        season: 'Annual'   #Use key name for seasons. Use 'All' for all defined seasons.
        statistic: 'mean'
        time_averaging: "periods" #Choose between periods, year, month
    102:
        id: 102
        name: 'Summer mean temperature (C)'
        variables: 'tas'
        season: 'Summer'   #Use key name for seasons. Use 'All' for all defined seasons.
        statistic: 'mean'
        time_averaging: "periods" #Choose between periods, year, month
    103:
        id: 103
        name: 'Annual mean temperature (C)'
        variables: 'tas'
        season: 'Annual'   #Use key name for seasons. Use 'All' for all defined seasons.
        statistic: 'mean'
        time_averaging: "year" #Choose between periods, year, month
    104:
        id: 104
        name: 'Annual mean precipitation (mm / day)'
        variables: 'pr'
        season: 'Annual'   #Use key name for seasons. Use 'All' for all defined seasons.
        statistic: 'mean'
        time_averaging: "year" #Choose between periods, year, month
