# Basic configuration file
#---------------------------
# This configuration file is intended to be used as a basic example and test
# dataset for the KAPy suite. It is loosely based on the configuration used in the
# Ghana Climate Atlas, but with simplifications to make it run faster. Sample datasets
# can be downloaded from https://download.dmi.dk/Research_Projects/KAPy/
# For instructions, see 

configurationTables:
    inputs:  'config/inputs.tsv'
    indicators: 'config/indicators.tsv'
    scenarios:  'config/scenarios.tsv'
    periods:  'config/periods.tsv'
    seasons: 'config/seasons.tsv'
outputGrid:
    regriddingEngine: 'None'

# Configuration options------------------------------------
arealstats:
    calcForMembers: False
dirs:
    variables: 'results/1.variables'
    indicators: 'results/2.indicators'
    regridded: 'results/3.commmon_grid'
    ensstats: 'results/4.ensstats'
    arealstats: 'results/5.areal_statistics'
    notebooks: 'results/6.notebooks'
    plots: 'results/6.plots'
ensembles:
    upperPercentile: 90
    centralPercentile: 50
    lowerPercentile: 10
primVars:  #Otherwise store as pickled Xarray objects
    storeAsNetCDF: True
