# Basic configuration file
#---------------------------
# This configuration file is intended to be used as a basic example and test
# dataset for the KAPy suite. It is loosely based on the configuration used in the
# Ghana Climate Atlas, but with simplifications to make it run faster. Sample datasets
# can be downloaded from https://download.dmi.dk/Research_Projects/KAPy/

configurationTables:
    inputs:  '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/config/inputs_testcase_3.tsv'
    indicators: '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/config/indicators_testcase_3.tsv'
    scenarios:  '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/config/scenarios_testcase_3.tsv'
    periods:  '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/config/periods_testcase_3.tsv'
    seasons: '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/config/seasons_testcase_3.tsv'
dirs:
    variables: '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/results/1.variables'
    indicators: '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/results/2.indicators'
    regridded: '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/results/3.commmon_grid'
    ensstats: '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/results/4.ensstats'
    arealstats: '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/results/5.areal_statistics'
    plots: '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/results/6.plots'
    netcdf: '/lustre/storeC-ext/users/klimakverna/development/tyge/KAPy/results/7.netcdf'

# Configuration options------------------------------------
arealstats:
    calcForMembers: False
ensembles:
    upperPercentile: 99
    centralPercentile: 95
    lowerPercentile: 1
cutouts:
    method: None
outputGrid:
    regriddingEngine: None
