# Basic configuration file
#---------------------------
# This configuration file is intended to be used as a basic example and test
# dataset for the KAPy suite. It is loosely based on the configuration used in the
# Ghana Climate Atlas, but with simplifications to make it run faster. Sample datasets
# can be downloaded from https://download.dmi.dk/Research_Projects/KAPy/
# For instructions, see 

configurationTables:
    inputs:  '/lustre/storeC-ext/users/klimakverna/development/kaja/KAPy/config/inputs_testcase_6.tsv'
    indicators: '/lustre/storeC-ext/users/klimakverna/development/kaja/KAPy/config/indicators_testcase_6.tsv'
    scenarios:  '/lustre/storeC-ext/users/klimakverna/development/kaja/KAPy/config/scenarios_testcase_6.tsv'
    periods:  '/lustre/storeC-ext/users/klimakverna/development/kaja/KAPy/config/periods_testcase_6.tsv'
    seasons: '/lustre/storeC-ext/users/klimakverna/development/kaja/KAPy/config/seasons.tsv'
    region: '/lustre/storeC-ext/users/klimakverna/development/kaja/KAPy/config/region_testcase_6.tsv'
dirs:
    region: '/lustre/storeC-ext/users/klimakverna/development/output/testcase_6/cnrm_aladin'

# Configuration options------------------------------------
arealstats:
    calcForMembers: False
cutouts:
    method: 'lonlatbox'
    xmin: 4.088
    xmax: 31.761
    ymin: 57.759
    ymax: 71.384
ensembles:
    upperPercentile: 90
    centralPercentile: 50
    lowerPercentile: 10
outputGrid:
    regriddingEngine: None