# Basic configuration file
#---------------------------
# This configuration file is intended to be used as a basic example and test
# dataset for the KAPy suite. It is loosely based on the configuration used in the
# Ghana Climate Atlas, but with simplifications to make it run faster. Sample datasets
# can be downloaded from https://download.dmi.dk/Research_Projects/KAPy/
# For instructions, see 

domain:
    xmin: -4
    xmax: 2
    dx: 0.1
    ymin: 4
    ymax: 12
    dy: 0.1
inputs:  'config/inputs.tsv'
indicators: 'config/indicators.tsv'
scenarios:  'config/scenarios.tsv'
notebooks: 'workflow/notebooks/Output_overview.py.ipynb'
periods:  'config/periods.tsv'
seasons: 'config/seasons.tsv'

# Configuration options------------------------------------
arealstats:
    calcForMembers: False
dirs:
    workDir: 'results'
    # search: '0.search'
    # URLs: '1.URLs'
    inputs: '1.inputs'
    primVars: '2.primVars'
    bc: '3.biascorrected_variables'
    indicators: '4.indicators'
    regridded: '5.commmon_grid'
    ensstats: '6.ensstats'
    arealstats: '7.areal_statistics'
    notebooks: 'notebooks'
ensembles:
    upperPercentile: 90
    centralPercentile: 50
    lowerPercentile: 10
primVars:  #Otherwise store as pickled Xarray objects
    storeAsNetCDF: True
regridding:
    method: 'bilinear'  #Regridding method used by xesmf.Regridder()
