sample_table: "config/testcase_2.tsv"
mmd_output: "/lustre/storeC-ext/users/klimakverna/development/output/testcase_2/mmd"
nc_output: "/lustre/storeC-ext/users/klimakverna/development/output/testcase_2"
input_base: "/lustre/storeC-ext/users/kin2100/"