#Default configuration file
#
#Keys defined here are used as the default value across all KAPy if they not overridden by
#values defined in the individual configurations. All parameters used in KAPy are defined
#here, so this file can also be used as an exhaustive list of configuration options
#Keys are sorted in alphabetical order at the first level at least

arealstats:
    calcForMembers: False
chunks:  #Otherwise store as pickled Xarray objects
    storeAsNetCDF: True
dirs:
    workDir: 'workDir'
    # search: '0.search'
    # URLs: '1.URLs'
    inputs: '1.inputs'
    chunks: '2.chunks'
    bc: '3.biascorrected_variables'
    indicators: '4.indicators'
    regridded: '5.commmon_grid'
    ensstats: '6.ensstats'
    arealstats: '7.areal_statistics'
    notebooks: 'notebooks'
domain: #Defined in separate config.yaml
ensembles:
    percentiles: [10,50,90]
indicators:  #Defined in separate config.yaml
inputs: #Defined in separate config.yaml
periods:  #Define periods here. The period with the lowest ID is used as the reference period
    period1:
        id: 1
        name: 'Historical\n(1981-2010)'
        start: 1981
        end: 2010
    period2:
        id: 2
        name: 'Start of century\n(2011-2040)'
        start: 2011
        end: 2040
    period3:
        id: 3
        name: 'Mid-century\n(2041-2070)'
        start: 2041
        end: 2070
    period4:
        id: 4
        name: 'End-of-century\n(2071-2100)'
        start: 2071
        end: 2100
regridding:
    method: 'bilinear'  #Regridding method used by xesmf.Regridder()
scenarios:  #A combination of CMIP experiments that are basis for analysis
    rcp26:
        id: 26
        shortname: 'rcp26'
        description: 'Low emissions scenario (RCP2.6)'
        experiments: ['historical','rcp26']
    rcp45:
        id: 45
        shortname: 'rcp45'
        description: 'Medium emissions scenario (RCP4.5)'
        experiments: ['historical','rcp45']
    rcp85:
        id: 85
        shortname: 'rcp85'
        description: 'High emissions scenario (RCP8.5)'
        experiments: ['historical','rcp85']
seasons:
    Annual:
        id: 0
        name: 'Annual'
        months: [1,2,3,4,5,6,7,8,9,10,11,12]
    Winter:
        id: 1
        name: 'Winter (DJF)'
        months: [12,1,2]
    Spring:
        id: 2
        name: 'Spring (MAM)'
        months: [3,4,5]
    Summer:
        id: 3
        name: 'Summer (JJA)'
        months: [6,7,8]
    Autumn:
        id: 4
        name: 'Autumn (SON)'
        months: [9,10,11]
